@url = https://8080-juaanlxx-gamessw2024-uu7vv8d60lv.ws-us116.gitpod.io

GET {{url}}/jogos

###

GET {{url}}/jogos/1

##

POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Crash Bandicoot",
    "plataformas": [
        {"id": 1},
        {"id": 2}
    ]
}